upstream version 7.1.1

diff --git a/tests/02-functions b/tests/02-functions
--- a/tests/02-functions
+++ b/tests/02-functions
@@ -1,39 +1,39 @@
 fatal() {
   for line in "$@"; do
-    echo "$line" >&2
+    ${ECHO} "$line" >&2
   done
   exit 100;
 }
 
 grephdr() {
   # Search for the header line, and produce an error if it didn't match.
-  egrep "^$*$" "$QQHDR" >/dev/null 2>&1 || \
+  ${GREP} "^$*$" "$QQHDR" >/dev/null 2>&1 || \
   {
-    echo "Header is missing or wrong $1 line:";
-    grep -i "^$1" "$QQHDR"
+    ${ECHO} "Header is missing or wrong $1 line:";
+    ${GREP} -i "^$1" "$QQHDR"
     BUG="${BUG} headers"
     prompt "..............: "
   }
   # Remove any found lines from the header file
-  grep -iv "^$1" "$QQHDR" >"${TMP}hdr"
-  mv -f "${TMP}hdr" "$QQHDR"
+  ${GREP} -iv "^$1" "$QQHDR" >"${TMP}hdr"
+  ${MV} -f "${TMP}hdr" "$QQHDR"
 }
 
 grepbody() {
-  egrep "^$*$" "$QQBODY" >/dev/null 2>&1 || \
+  ${GREP} "^$*$" "$QQBODY" >/dev/null 2>&1 || \
   {
-    echo "Body is missing or wrong $1 line:";
-    grep -i "^$1" "$QQBODY"
+    ${ECHO} "Body is missing or wrong $1 line:";
+    ${GREP} -i "^$1" "$QQBODY"
     BUG="${BUG} body"
     prompt "..............: "
   }
 }
 
 grepbodynot() {
-  egrep "^$*" "$QQBODY" >/dev/null 2>&1 && \
+  ${GREP} "^$*" "$QQBODY" >/dev/null 2>&1 && \
   {
-    echo "Body contains extraneous $1 line:";
-    grep -i "^$1" "$QQBODY"
+    ${ECHO} "Body contains extraneous $1 line:";
+    ${GREP} -i "^$1" "$QQBODY"
     BUG="${BUG} body"
     prompt "..............: "
   }
@@ -68,8 +68,8 @@ grephdr_empty() {
   # Use this after all other grephdr checks to ensure nothing else was output
   test -s "$QQHDR" && \
   {
-    echo "Headers contained extra lines:"
-    cat "$QQHDR"
+    ${ECHO} "Headers contained extra lines:"
+    ${CAT} "$QQHDR"
     BUG="${BUG} headers"
   }
 }
@@ -77,7 +77,7 @@ grephdr_empty() {
 checkenv()
 {
   msg="$1"
-  head -n 1 "$QQENV" | grep "^F$2$" >/dev/null \
+  ${HEAD} -n 1 "$QQENV" | grep "^F$2$" >/dev/null \
   || fatal "envelope for $msg has wrong sender"
   test $# = $(wc -l <"$QQENV") \
   || fatal "envelope for $msg has wrong number of recipients"
@@ -93,44 +93,44 @@ checkenv()
 ###############################
 make_body()
 {
-  echo "This is a simple message body"
-  echo "--bound123ary"
-  echo "Content-type: Text/pLAIn"
-  echo
-  echo "plain text"
-  echo "--bound123ary"
-  echo "Content-type: texT/Html"
-  echo
-  echo "html text"
-  echo "--bound123ary--"
-  echo
-  echo "junk after boundary"
+  ${ECHO} "This is a simple message body"
+  ${ECHO} "--bound123ary"
+  ${ECHO} "Content-type: Text/pLAIn"
+  ${ECHO}
+  ${ECHO} "plain text"
+  ${ECHO} "--bound123ary"
+  ${ECHO} "Content-type: texT/Html"
+  ${ECHO}
+  ${ECHO} "html text"
+  ${ECHO} "--bound123ary--"
+  ${ECHO}
+  ${ECHO} "junk after boundary"
   return 0
 }
 
 qqclean()
 {
-  rm -f "$QQBODY" "$QQENV" "$QQHDR" "$QQMSG" "$QQMSG".*
+  ${RM} -f "$QQBODY" "$QQENV" "$QQHDR" "$QQMSG" "$QQMSG".*
 }
 
 make_message()
 {
-  echo "ReCEIved: #LAST#"
-  echo "ReCeIved: #PENULTIMATE#"
-  echo "retuRN-RECeipt-to: nobody"
-  echo "To: $TO"
-  echo "CC: "
-  echo " $CC"
-  echo "FROM: $FROM"
+  ${ECHO} "ReCEIved: #LAST#"
+  ${ECHO} "ReCeIved: #PENULTIMATE#"
+  ${ECHO} "retuRN-RECeipt-to: nobody"
+  ${ECHO} "To: $TO"
+  ${ECHO} "CC: "
+  ${ECHO} " $CC"
+  ${ECHO} "FROM: $FROM"
   if [ ! -z "$CONTENT" ]; then
-	echo "MIME-Version: 1.0"
-	echo "Content-type: $CONTENT;"
-	echo " boundary=bound123ary${AFTERBOUND}"
+	${ECHO} "MIME-Version: 1.0"
+	${ECHO} "Content-type: $CONTENT;"
+	${ECHO} " boundary=bound123ary${AFTERBOUND}"
   fi
   if [ ! -z "$SUBJECT" ]; then
-	echo "Subject: $SUBJECT"
+	${ECHO} "Subject: $SUBJECT"
   fi
-  echo
+  ${ECHO}
   make_body
   return 0
 }
@@ -140,43 +140,18 @@ make_message()
 #########################
 exists() {
   for file in "$@"; do
-    test -e "$file" || return 1
+    ${TEST} -e "$file" || return 1
   done
   return 0
 }
 
 msgexists() {
-  test -s "$QQMSG" -a -s "${QQENV}"
+  ${TEST} -s "$QQMSG" -a -s "${QQENV}"
 }
 
 #######################################
 # Extract parts of the message header #
 #######################################
 gethdr() {
-    sed -e "/^$1:/!d; s/[^ ]* *//;" "$QQHDR"
-}
-
-##########################################
-# Run ezmlm-manage and check the results #
-##########################################
-check_manage() {
-    local name=$1
-    local options=$2
-    local exit=$3
-    local exitmsg="$4"
-    local text=$5
-    local sender="$6"
-    shift 6
-    ${EZBIN}/ezmlm-manage -a $options "$DIR" < "$TMP" > "$ERR" 2>&1
-    local e=$?
-    test $e -eq $exit || fatal "ezmlm-manage ($name) $exitmsg (exit $e)"
-    if [ -n "$text" ]
-    then
-	grep "ezmlm-manage: info: sending $text$" "$ERR" >/dev/null 2>&1 \
-	    || fatal "ezmlm-manage ($name) sent wrong text (should be $text)"
-    fi
-    if [ -n "$sender" ]
-    then
-	checkenv $name "$sender" "$@"
-    fi
+    ${SED} -e "/^$1:/!d; s/[^ ]* *//;" "$QQHDR"
 }
diff --git a/tests/160-ezmlm-manage b/tests/160-ezmlm-manage
--- a/tests/160-ezmlm-manage
+++ b/tests/160-ezmlm-manage
@@ -4,130 +4,166 @@
 
   prompt "ezmlm-manage (1/2):   "
 
+  LOCAL="$LOC-unsubscribe"
   DEFAULT='unsubscribe'
   SENDER="${SND}@$HOST"
 
   ${EZBIN}/ezmlm-sub "$DIR" "$SENDER"
-  check_manage unsubscribe-U -U 0 "failed with -U" unsub-ok \
-      "$LOC-return-@$HOST" "$SENDER"
+  ${EZBIN}/ezmlm-manage -U "$DIR" </dev/null >"$ERR" 2>&1 || \
+	fatal "failed with -U"
+  checkenv unsubscribe-U "$LOC-return-@$HOST" "$SENDER"
   ${EZBIN}/ezmlm-issubn "$DIR" && \
 	fatal "unsubscribe with -U failed"
 
   ${EZBIN}/ezmlm-sub "$DIR" "$SENDER"
   touch "$DIR"/nounsubconfirm
-  check_manage unsubscribe-nounsubconfirm '' 0 "failed with nounsubconfirm" unsub-ok \
-      "$LOC-return-@$HOST" "$SENDER"
+  ${EZBIN}/ezmlm-manage "$DIR" </dev/null >"$ERR" 2>&1 || \
+	fatal "failed with nounsubconfirm"
+  checkenv unsubscribe-nounsubconfirm "$LOC-return-@$HOST" "$SENDER"
   ${EZBIN}/ezmlm-issubn "$DIR" && \
 	fatal "unsubscribe with nounsubconfirm failed"
-  rm "$DIR"/nounsubconfirm
+  ${RM} "$DIR"/nounsubconfirm
 
+  LOCAL="$LOC-digest-subscribe"
+  DEFAULT='digest-subscribe'
   ${EZBIN}/ezmlm-unsub "$DIR" digest "$SENDER"
 
 # test that access to the deny db is restricted to remote admins
+  LOCAL="$LOC-deny-subscribe"
   DEFAULT='deny-subscribe'
-  check_manage deny '' 100 'Deny open to regular subscribers'
-
+  ${EZBIN}/ezmlm-manage "$DIR" </dev/null >/dev/null 2>&1 && \
+	{
+	 ${ECHO} "Deny open to regular subscribers: 0.31 bug, OK in 0.321."
+	 prompt "ezmlm-manage ...      "
+	 BUG="${BUG} deny"
+	}
+  checkenv deny "$LOC-return-@$HOST" "$SENDER"
   SENDER="${MOD}@$HOST"
   ${EZBIN}/ezmlm-sub "$DIR" mod "$SENDER" || exit 100
-  check_manage admin-deny '' 0 'Deny access denied to remote admin' mod-sub-confirm \
-      "$LOC-deny-return-@$HOST" "$SENDER"
+  ${EZBIN}/ezmlm-manage "$DIR" </dev/null > "$ERR" 2>&1 || \
+	fatal "Deny access denied to remote admin!"
+  checkenv admin-deny "$LOC-deny-return-@$HOST" "$SENDER"
 
 # make non-moderated
-  rm -f "${DIR}/modsub" || \
-	{ echo "Failed to remove DIR/modsub"; exit 99; }
+  ${RM} -f "${DIR}/modsub" || \
+	{ ${ECHO} "Failed to remove DIR/modsub"; exit 99; }
 
 # make non-remote
-  rm -f "${DIR}/remote" || \
-	{ echo "Failed to remove DIR/remote"; exit 99; }
-  check_manage noremote-deny '' 100 'Deny even without remote/modsub'
+  ${RM} -f "${DIR}/remote" || \
+	{ ${ECHO} "Failed to remove DIR/remote"; exit 99; }
+  ${EZBIN}/ezmlm-manage "$DIR" </dev/null > "$ERR" 2>&1 && \
+	{
+	 ${ECHO} "Deny even without remote/modsub: 0.31 bug, OK in 0.321."
+	 prompt "ezmlm-manage ...      "
+	 BUG="${BUG} deny"
+	}
+  checkenv noremote-deny "$LOC-deny-return-@$HOST" "$SENDER"
 
-# restore remote/SENDER/mod/DEFAULT
+# restore remote/SENDER/mod/LOCAL/DEFAULT
   ${EZBIN}/ezmlm-unsub "$DIR" mod "$SENDER" || exit 100
   SENDER="${SND}@$HOST"		# restore order
   touch "${DIR}/remote" || \
-	{ echo "Failed to create DIR/remote"; exit 99; }
-  DEFAULT='digest-subscribe'
+	{ ${ECHO} "Failed to remove DIR/remote"; exit 99; }
+  LOCAL="$LOC-digest-subscribe"
+	DEFAULT='digest-subscribe'
 
-  check_manage digest-subscribe-S -S 0 'failed with -S' sub-ok \
-      "$LOC-digest-return-@$HOST" "$SENDER"
+  ${EZBIN}/ezmlm-manage -S "$DIR" </dev/null >"$ERR" 2>&1 || \
+	fatal "failed with -S"
+  checkenv digest-subscribe-S "$LOC-digest-return-@$HOST" "$SENDER"
   ${EZBIN}/ezmlm-issubn "$DIR" digest || \
 	fatal "digest-subscribe with -S failed"
 
   ${EZBIN}/ezmlm-unsub "$DIR" digest "$SENDER"
   touch "$DIR"/nosubconfirm
-  check_manage digest-subscribe-nosubconfirm '' 0 'failed with nosubconfirm' sub-ok \
-      "$LOC-digest-return-@$HOST" "$SENDER"
+  ${EZBIN}/ezmlm-manage "$DIR" </dev/null >"$ERR" 2>&1 || \
+	fatal "failed with nosubconfirm"
+  checkenv digest-subscribe-nosubconfirm "$LOC-digest-return-@$HOST" "$SENDER"
   ${EZBIN}/ezmlm-issubn "$DIR" digest || \
 	fatal "digest-subscribe with nosubconfirm failed"
-  rm "$DIR"/nosubconfirm
+  ${RM} "$DIR"/nosubconfirm
 
   ${EZBIN}/ezmlm-unsub "$DIR" digest "$SENDER"
   touch "${DIR}/modsub" || \
-	{ echo "Failed to restore DIR/modsub"; exit 99; }
+	{ ${ECHO} "Failed to restore DIR/modsub"; exit 99; }
 
   SENDER="${MAN}@$HOST"
 
-  echo "X-num: sub1" > "$TMP"
-  echo "From: Mr. User requests <${MAN}@$HOST>" >> "$TMP"
-  echo >> "$TMP"
-  check_manage sub1 '' 0 'digest-subscribe with request failed' sub-confirm \
-      "$LOC-digest-return-@$HOST" "$SENDER"
+  ${ECHO} "X-num: sub1" > "$TMP"
+  ${ECHO} "From: Mr. User requests <${MAN}@$HOST>" >> "$TMP"
+  ${ECHO} >> "$TMP"
+  ${EZBIN}/ezmlm-manage "$DIR" < "$TMP" \
+		>"$ERR" 2>&1 || \
+	fatal "digest-subscribe with request failed"
+  checkenv sub1 "$LOC-digest-return-@$HOST" "$SENDER"
 
-  grep T"${MAN}@$HOST" "$QQENV" >/dev/null 2>&1 || \
+  ${GREP} T"${MAN}@$HOST" "$QQENV" >/dev/null 2>&1 || \
 	fatal "failed getting digest-subscribe confirm request"
 
   # Add moderator
   ${EZBIN}/ezmlm-sub "$DIR" mod "${MOD}@$HOST"
 
-  DEFAULT=`grep "Reply-To:" "$QQMSG" | cut -d' ' -f2 | cut -d'@' -f1 | cut -c"$LOCLEN"-` || \
+  LOCAL=`${GREP} "Reply-To:" "$QQMSG" | cut -d' ' -f2 | cut -d'@' -f1` || \
 	fatal "failed to find confirm address in -subscribe reply"
   qqclean
-  echo "X-num: sub3" > "$TMP"
-  echo "From: Mr. User confirms <$SENDER>" >> "$TMP"
-  echo >> "$TMP"
-  check_manage sub3 '' 0 'failed to send user conf for sub1' mod-sub-confirm \
-      "$LOC-digest-return-@$HOST" "$MOD@$HOST"
+  DEFAULT=`${ECHO} "$LOCAL" | cut -c"$LOCLEN"-`
+  ${ECHO} "X-num: sub3" > "$TMP"
+  ${ECHO} "From: Mr. User confirms <$SENDER>" >> "$TMP"
+  ${ECHO} >> "$TMP"
+  ${EZBIN}/ezmlm-manage "$DIR" < "$TMP" \
+		>"$ERR" 2>&1 || \
+	fatal "failed to send user conf for sub1"
+  checkenv sub3 "$LOC-digest-return-@$HOST" "$MOD@$HOST"
   msgexists || \
 	fatal "failed to receive user conf for sub1"
   SENDER="${MOD}@$HOST"
   ${EZBIN}/ezmlm-issubn "$DIR" && \
 	fatal "unsub without mod for moderated list failed"
-  grep 'sub3' "$QQMSG" >/dev/null 2>&1 || \
+  ${GREP} 'sub3' "$QQMSG" >/dev/null 2>&1 || \
 	fatal "failed getting subscribe moderation confirm request"
 
   # confirm subscription request
-  DEFAULT=`grep "Reply-To:" "$QQMSG" | cut -d' ' -f2 | cut -d'@' -f1 | cut -c"$LOCLEN-"` || \
+  LOCAL=`${GREP} "Reply-To:" "$QQMSG" | cut -d' ' -f2 | cut -d'@' -f1` || \
 	fatal "no confirm address in sub3 mod confirm request"
-  echo "X-num: modR1" > "$TMP"
-  echo "FROM: moderator agrees <$SENDER>" >> "$TMP"
-  echo >> "$TMP"
-  check_manage modR1 '' 0 'failed to send digest sub mod accept for sub3' sub-ok \
-      "$LOC-digest-return-@$HOST" "$MAN@$HOST"
+  DEFAULT=`${ECHO} "$LOCAL" | cut -c"$LOCLEN"-`
+  ${ECHO} "X-num: modR1" > "$TMP"
+  ${ECHO} "FROM: moderator agrees <$SENDER>" >> "$TMP"
+  ${ECHO} >> "$TMP"
+  ${EZBIN}/ezmlm-manage ${SW_FROM} "$DIR" < "$TMP"\
+		>/dev/null 2>&1 || \
+	fatal "failed to send digest sub mod accept for sub3"
+  checkenv modR1 "$LOC-digest-return-@$HOST" "$MAN@$HOST"
 
   SENDER="${MAN}@$HOST"
   ${EZBIN}/ezmlm-sub "$DIR" "$SENDER"
+  LOCAL="$LOC-unsubscribe"
   DEFAULT='unsubscribe'
-  echo "X-num: sub2" > "$TMP"
-  check_manage sub2 '' 0 'unsubscribe request failed' unsub-confirm \
-      "$LOC-return-@$HOST" "$SENDER"
+  ${ECHO} "X-num: sub2" > "$TMP"
+  ${EZBIN}/ezmlm-manage "$DIR" < "$TMP" >"$ERR" 2>&1 || \
+	fatal "unsubscribe request failed"
+  checkenv sub2 "$LOC-return-@$HOST" "$SENDER"
 
-  DEFAULT=`grep "Reply-To:" "$QQMSG" | cut -d' ' -f2 | cut -d'@' -f1 | cut -c"$LOCLEN"-` || \
+  LOCAL=`${GREP} "Reply-To:" "$QQMSG" | cut -d' ' -f2 | cut -d'@' -f1` || \
 	fatal "failed to find confirm address in -unsubscribe reply"
-  echo "X-num: sub4" > "$TMP"
-  check_manage sub4 '' 0 'failed to send conf for sub2' unsub-ok \
-      "$LOC-return-@$HOST" "$SENDER"
+  DEFAULT=`${ECHO} "$LOCAL" | cut -c"$LOCLEN"-`
+  ${ECHO} "X-num: sub4" > "$TMP"
+  ${EZBIN}/ezmlm-manage "$DIR" < "$TMP" >/dev/null 2>&1 || \
+	fatal "failed to send conf for sub2"
+  checkenv sub4 "$LOC-return-@$HOST" "$SENDER"
 
 # -get function for backwards compatibility
+  LOCAL="$LOC-get.1"
   DEFAULT='get.1'
-  echo "X-num: manget1" > "$TMP"
-  check_manage get.1 '' 0 'get failed' get \
-      "$LOC-return-@$HOST" "$SENDER"
+  ${ECHO} "X-num: manget1" > "$TMP"
+  ${EZBIN}/ezmlm-manage "$DIR" < "$TMP" >"$ERR" 2>&1 || \
+	fatal "get failed"
+  checkenv get.1 "$LOC-return-@$HOST" "$SENDER"
 
   # Check -get.1 reply
-  grep 'msg1' "$QQMSG" >/dev/null || \
+  ${GREP} 'msg1' "$QQMSG" >/dev/null || \
 	fatal "get.1 failed to return archived message"
 
 # -C should disable it
-  check_manage get-C -C 100 '-C failed to disable -get'
+  ${EZBIN}/ezmlm-manage -C "$DIR" < "$TMP" >"$ERR" 2>&1 && \
+	fatal "-C failed to disable -get"
 
-  echo "OK"
+  ${ECHO} "OK"
